# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "What is Eclipse Keyple"
  url = "what-is-keyple/"
  weight = 10

[[main]]
  name = "What is Eclipse Keyple 2"
  url = "what-is-keyple-page/"
  weight = 20

[[main]]
  name = "News"
  url = "#news"
  weight = 30

[[main]]
  name = "Documentation"
  url = "docs/"
  weight = 40

[[main]]
  name = "Community"
  url = "community/"
  weight = 50

[[main]]
  name = "Support & Trainings"
  url = "community/support-trainings/"
  weight = 60