# SITE SETUP
# Guide: https://sourcethemes.com/academic/docs/get-started/
# Documentation: https://sourcethemes.com/academic/docs/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[search]`).

############################
## Theme
############################

# Choose a theme.
#   Latest themes (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in themes in `themes/academic/data/themes/`
#   Browse user installed themes in `data/themes/`
theme = "keyple-theme"

# Enable users to switch between day and night mode?
day_night = false

# Override the theme's font set (optional).
#   Latest font sets (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in font sets in `themes/academic/data/fonts/`
#   Browse user installed font sets in `data/fonts/`
font = "keyple-font"

# Choose a font size.
# Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)
font_size = "M"

############################
## Basic Info
############################

# Website type
#   Improve how search engines understand your site.
#   For personal sites, choose "Person".
#   For organizations and projects, choose from https://schema.org/Organization#subtypes
#   E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
site_type = "Project"

# Local business type (optional)
# If you entered "LocalBusiness" above, choose the type of business from https://schema.org/LocalBusiness#subtypes
local_business_type = ""

# Organization name (optional)
# Enter an organization or project name. Defaults to the site title from `config.toml`.
org_name = "Eclipse"

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description = "Eclipse KeypleÂ® accelerates the development through a universal, open and modular platform that provides high-level APIs and ensures application reliability and compliance."

############################
## Site Features
############################

# Enable source code highlighting? true/false
# Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
highlight = true
highlight_languages = ["java", "groovy", "xml", "kotlin", "cpp", "gradle", "ini"]  # Add support for highlighting additional languages
# highlight_style = "github"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/
highlight_style = "darcula"

# Enable LaTeX math rendering? true/false
math = false

# Enable diagram rendering? true/false
diagram = false

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack = true

# Enable visitors to edit pages?
edit_page = {repo_url = "https://github.com/eclipse/keyple-website", content_dir = "", repo_branch = "master", editable = {docs = true, page = true, post = true}}

# Show related content at the bottom of pages?
show_related = {docs = true, page = true, post = true, project = true, publication = true, talk = true}

############################
## Contact details
## Additionally, for organizations, these details may be used to enrich search engine results.
############################

# Contact links
contact_links = [
  {icon = "comments", icon_pack = "fas", name = "Discuss on Forum", link = "https://www.eclipse.org/forums/index.php/f/446/"},
  ]

############################
## Social
############################

# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image = ""


############################
## Regional Settings
############################

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02" or "January 2006"
date_format = "Mon, Jan 2, 2006"
#   Examples: "3:04 pm" or "15:04"
time_format = "15:04"

# Address format (choose from the [address_formats] list below or add you own to the list).
address_format = "en-us"

############################
## Advanced
############################

# Main menu alignment (l = left, c = center, r = right) and logo options.
main_menu = {align = "c", show_logo = true}

# Show estimated reading time for posts? (true/false)
reading_time = true

# Display next/previous section pager? (true/false)
section_pager = false
docs_section_pager = false  # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing = true

# Show a copyright license from creativecommons.org in the site footer?
# Page specific copyright licenses are also possible by adding this option to a page's front matter.
copyright_license = {enable = false, allow_derivatives = true, share_alike = true, allow_commercial = true, notice = "This work is licensed under {license}"}

# Highlight the site author (superuser) in author lists? (true/false)
highlight_superuser = false

# Link authors to their profile page? (true/false)
link_authors = false

# Abstract length (characters) in the Compact and Portfolio Card list views. Also, see `summaryLength` in `config.toml`.
abstract_length = 135

# Load JS plugins
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_js = ["custom"]

# Avatars.
# An avatar is an image that appears next to a user's name.
# An avatar can be uploaded as an image named `avatar` to each user's profile or fetched from Gravatar.com.
[avatar]
  # Get user avatars from Gravatar.com? (true/false)
  gravatar = false

  # Choose a shape for avatar images. Options: circle, square.
  shape = "circle"

# Available address formats.
[address_formats]
  en-us = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ' ', '']}
  en-gb = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ', ', '']}
  de = {order = ['street', 'postcode', 'city'], delimiters = ['<br>', ' ', '']}
  fr-fr = {order = ['street', 'postcode', 'city'], delimiters = ['<br>', ' ', '']}
  zh = {order = ['postcode', 'region', 'city', 'street'], delimiters = [' ', ' ', ' ', '']}

# Configuration of publication pages.
[publications]
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02" or "January 2006"
  date_format = "Mon, Jan 2, 2006"

  # Citation style ("apa" or "mla")
  citation_style = "apa"

# Configuration of project pages.
[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 2
  publication_view = 2
  talk_view = 2

############################
## Comments
############################
[comments]
  # Comment provider:
  #   0: Disabled
  #   1: Disqus (https://disqus.com)
  #   2: Commento (https://commento.io)
  engine = 0

  # Which page types are commentable?
  commentable = {page = true, post = true, docs = true, project = true, publication = true, talk = true}

  # Configuration of Disqus.
  [comments.disqus]
    shortname = ""  # Paste the shortname from your Disqus dashboard.
    show_count = true  # Show comment count in page header? (true/false)

  # Configuration of Commento.
  [comments.commento]
    # If self-hosting Commento, enter its URL here (e.g. "https://commento.?.com"), otherwise leave empty.
    url = ""

############################
## Search
############################
[search]
  # Search provider:
  #   0: No search engine
  #   1: Academic (built-in)
  #   2: Algolia (https://www.algolia.com)
  engine = 1

############################
## Marketing
############################
[marketing]
  google_analytics = ""
  google_tag_manager = "GTM-5WLCZXC"

############################
## Keyple components versions
############################
[keyple_version]
  calypsonet_terminal_reader_java_api = "1.0.0"
  calypsonet_terminal_reader_java_api_dynamic_gradle = "1.0.+"
  calypsonet_terminal_reader_java_api_dynamic_maven = "[1.0.0,1.1.0)"

  calypsonet_terminal_card_java_api = "1.0.0"
  calypsonet_terminal_card_java_api_dynamic_gradle = "1.0.+"
  calypsonet_terminal_card_java_api_dynamic_maven = "[1.0.0,1.1.0)"

  calypsonet_terminal_calypso_java_api_dynamic_gradle = "1.0.+"
  calypsonet_terminal_calypso_java_api_dynamic_maven = "[1.0.0,1.1.0)"

  keyple_card_calypso_java_lib = "2.0.0"

  keyple_card_generic_java_lib = "2.0.0"

  keyple_common_java_api = "2.0.0"
  keyple_common_java_api_dynamic_gradle = "2.0.+"
  keyple_common_java_api_dynamic_maven = "[2.0.0,2.1.0)"

  keyple_distributed_local_java_api = "2.0.0"
  keyple_distributed_local_java_api_dynamic_gradle = "2.0.+"
  keyple_distributed_local_java_api_dynamic_maven = "[2.0.0,2.1.0)"

  keyple_distributed_local_java_lib = "2.0.0"

  keyple_distributed_network_java_lib = "2.0.0"

  keyple_distributed_remote_java_api = "2.0.0"
  keyple_distributed_remote_java_api_dynamic_gradle = "2.0.+"
  keyple_distributed_remote_java_api_dynamic_maven = "[2.0.0,2.1.0)"

  keyple_distributed_remote_java_lib = "2.0.0"

  keyple_plugin_android_nfc_java_lib = "2.0.0"

  keyple_plugin_android_omapi_java_lib = "2.0.0"

  keyple_plugin_java_api = "2.0.0"
  keyple_plugin_java_api_dynamic_gradle = "2.0.+"
  keyple_plugin_java_api_dynamic_maven = "[2.0.0,2.1.0)"

  keyple_plugin_pcsc_java_lib = "2.0.0"

  keyple_plugin_stub_java_lib = "2.0.0"

  keyple_service_java_lib = "2.0.0"

  keyple_service_resource_java_lib = "2.0.0"

  keyple_util_java_lib = "2.0.0"
  keyple_util_java_lib_dynamic_gradle = "2.+"
  keyple_util_java_lib_dynamic_maven = "[2.0.0,3.0.0)"

  keyple_java = "1.0.0"
  keyple_cpp = "0.9.0"
